config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  root "static_pages#top"
  get "map", to: "map_pages#map"
  resources :tourist_spots, only: %i[index] do
    collection do
      get :bookmarks
    end
  end
  resources :bookmarks, only: %i[create destroy]
  resources :movement_methods, only: %i[index]
  resources :inquiries, only: %i[new create] do
    collection do
      match :confirm, via: %i[get post]
      match :back, via: %i[get post]
    end
  end
  get "thank_you", to: "inquiries#thank_you", as: "thank_you"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :tourist_spot

  validates :user_id, uniqueness: { scope: :tourist_spot_id }
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :message, presence: true
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/tourist_spot.rb
class TouristSpot < ApplicationRecord
  has_many :bookmarks, dependent: :destroy

  def bookmarked?(user)
    bookmarks.exists?(user: user)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[google_oauth2]
  validates :name, presence: true, length: { minimum: 2 }
  validates :profile, length: { maximum: 200 }
  has_many :sns_credential, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_tourist_spots, through: :bookmarks, source: :tourist_spot

  class << self
    def without_sns_data(auth)
      user = User.where(email: auth.info.email).first

      if user.present?
        sns = SnsCredential.create(
          uid: auth.uid,
          provider: auth.provider,
          user_id: user.id
        )
      else
        user = User.create(
          name: auth.info.name,   
          email: auth.info.email,
          password: Devise.friendly_token(10)
        )
        sns = SnsCredential.create(
          user_id: user.id,
          uid: auth.uid,
          provider: auth.provider
        )
      end
      { user:, sns: }
    end

    def with_sns_data(auth, snscredential)
      user = User.where(id: snscredential.user_id).first
      if user.blank?
        user = User.create(
          name: auth.info.name,
          email: auth.info.email,
          password: Devise.friendly_token(10)
        )
      end
      { user: }
    end

    def find_oauth(auth)
      uid = auth.uid
      provider = auth.provider
      snscredential = SnsCredential.where(uid:, provider:).first
      if snscredential.present?
        user = with_sns_data(auth, snscredential)[:user]
        sns = snscredential
      else
        user = without_sns_data(auth)[:user]
        sns = without_sns_data(auth)[:sns]
      end
      { user:, sns: }
    end
  end

  def bookmark(tourist_spot)
    bookmarks.create(tourist_spot: tourist_spot)
  end

  def unbookmark(tourist_spot)
    bookmark_tourist_spots.destroy(tourist_spot)
  end

  def bookmark?(tourist_spot)
    bookmark_tourist_spots.include?(tourist_spot)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :authenticate_user!

  def create
    tourist_spot = TouristSpot.find(params[:tourist_spot_id])
    bookmark = current_user.bookmark(tourist_spot)
    if bookmark.persisted?
      render json: { id: bookmark.id }, status: :created
    else
      render json: { error: bookmark.errors.full_messages.join(", ") }, status: :unprocessable_entity
    end
  end

  def destroy
    bookmark = current_user.bookmarks.find(params[:id])
    if bookmark.destroy
      render json: { message: "ブックマークを削除しました。" }, status: :ok
    else
      render json: { error: "ブックマークの削除に失敗しました。" }, status: :unprocessable_entity
    end
  end
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  skip_before_action :verify_authenticity_token

  def new
    @inquiry = Inquiry.new
  end

  def confirm
    if request.post?
      @inquiry = Inquiry.new(inquiry_params)
      if @inquiry.invalid?
        render :new
        return
      end
      session[:inquiry_data] = inquiry_params
    elsif session[:inquiry_data]
      @inquiry = Inquiry.new(session[:inquiry_data])
    else
      redirect_to new_inquiry_path
      return
    end
  end

  def back
    if request.get?
      redirect_to new_inquiry_path
      return
    end

    @inquiry = Inquiry.new(inquiry_params)
    render :new
  end

  def create
    @inquiry = Inquiry.new(inquiry_params)
    if @inquiry.save
      InquiryMailer.send_inquiry(@inquiry).deliver_now
      redirect_to thank_you_path
    else
      render :new
    end
  end

  def thank_you; end

  private

  def inquiry_params
    params.require(:inquiry).permit(:name, :email, :message)
  end
end

app/controllers/map_pages_controller.rb
class MapPagesController < ApplicationController
  def map; end
end

app/controllers/movement_methods_controller.rb
class MovementMethodsController < ApplicationController
  def index; end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def top; end
end

app/controllers/tourist_spots_controller.rb
class TouristSpotsController < ApplicationController
  def index
    @tourist_spots = TouristSpot.all.map do |spot|
      bookmark = spot.bookmarks.find_by(user: current_user)
      spot.as_json.merge(bookmark_id: bookmark&.id)
    end
    render json: @tourist_spots
  end

  def bookmarks
    @bookmark_tourist_spots = current_user.bookmark_tourist_spots.includes(:bookmarks).map do |spot|
      bookmark = spot.bookmarks.find_by(user: current_user)
      spot.as_json.merge(bookmark_id: bookmark&.id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_map_page?
      controller_name == "map_pages" && action_name == "map"
  end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/directions_helper.rb
module DirectionsHelper
  def google_maps_directions_url(destination)
    "https://www.google.com/maps/dir/?api=1&origin=現在地&destination=#{destination}"
  end
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/map_pages_helper.rb
module MapPagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tourist_spots_helper.rb
module TouristSpotsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head prefix="og: https://ogp.me/ns#">
    <title>HokurikuShienTravelersMap</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="twitter:card" content="summary_large_image" />
    <meta property="og:url" content="https://hokuriku-shien-travelers-map-c9f671e3c233.herokuapp.com/" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="北陸トラベラーズマップ" />
    <meta property="og:image" content="https://hokuriku-shien-travelers-map-c9f671e3c233.herokuapp.com/assets/hokuriku-travelers-map-14fbc93b8d4e579356dfd7f78341122d5b15f79293d73503459e20fad9124b19.jpg" />
    <meta property="og:site_name" content="北陸トラベラーズマップ" />
    <meta property="og:description" content="北陸トラベラーズマップは、まだあまり知られていない観光地含め多くの観光スポットがある北陸地方の魅力を発見し、北陸旅行への一助となるサービスです。" />

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <div class="page-container bg-info-subtle">
      <main class="content-wrap">
        <%= render "shared/header" %>
        <%= yield %>
      </main>
      <%= render "shared/footer" %>
    </div>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="d-flex justify-content-between align-items-center border-top p-3 bg-info">
  <p class="col-md-4 mb-0 text-body-secondary">&copy; Hokuriku-shien-Travelers-map</p>
  <%= link_to "利用規約", "https://kiyac.app/termsOfService/Rt8njknsXHttEQS9pOPe", class: "nav-link text-body-secondary" %>
  <%= link_to "お問い合わせ", new_inquiry_path, class: "nav-link text-body-secondary" %>
</footer>

app/views/shared/_header.html.erb
<header class="d-flex flex-wrap justify-content-center border-bottom p-2 bg-info">
  <a href="/" class="d-flex align-items-center me-md-auto link-body-emphasis text-decoration-none text-white">
    <h2>北陸トラベラーズマップ</h2>
  </a>

  <% if user_signed_in? %>
    <div class="dropdown">
      <button type="button" class="btn btn-outline-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
        メニュー
      </button>
      <ul class="dropdown-menu">
        <li><%= link_to "プロフィール", edit_user_registration_path, class: "dropdown-item" %></li>
        <li><%= link_to "ログアウト", destroy_user_session_path, class: "dropdown-item", data: { turbo_method: :delete } %></li>
        <li><%= link_to "マップ", map_path, class: "dropdown-item" %></li>
        <li><%= link_to "ブックマーク", bookmarks_tourist_spots_path, class: "dropdown-item" %></li>
        <li><%= link_to "行き方検索", movement_methods_path, class: "dropdown-item" %></li>
      </ul>
    </div>
  <% else %>
    <div class="dropdown">
      <button type="button" class="btn btn-outline-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
        メニュー
      </button>
      <ul class="dropdown-menu">
        <li><%= link_to "会員登録", new_user_registration_path, class: "dropdown-item" %></li>
        <li><%= link_to "ログイン", new_user_session_path, class: "dropdown-item" %></li>
        <li><%= link_to "マップ", map_path, class: "dropdown-item" %></li>
        <li><%= link_to "行き方検索", movement_methods_path, class: "dropdown-item" %></li>
      </ul>
    </div>
  <% end %>

  <% if is_map_page? %>
    <ul class="nav nav-pills justify-content-center align-items-center">
      <select id="category-selector" class="form-select form-select-sm" onchange="window.updateMarkers(this.value)">
        <option value="全て(マップに表示する観光地のカテゴリを選択)">全て(マップに表示する観光地のカテゴリを選択)</option>
        <option value="伝統文化・文化体験(体験施設)・歴史的建造物・城・庭園・神社・お寺・史跡">伝統文化・文化体験(体験施設)・歴史的建造物・城・庭園・神社・お寺・史跡</option>
        <option value="景勝地・展望台・港・自然">景勝地・展望台・港・自然</option>
        <option value="公園・植物園・ジオパーク・テーマパーク・遊園地・ビーチ・プール・スキー場・乗り物・その他アクティビティ">公園・植物園・ジオパーク・テーマパーク・遊園地・ビーチ・プール・スキー場・乗り物・その他アクティビティ</option>
        <option value="総合博物館">総合博物館</option>
        <option value="動物園・水族館・生き物関係の博物館">動物園・水族館・生き物関係の博物館</option>
        <option value="博物館(伝統文化・工芸(和風)・歴史・文学・偉人)">博物館(伝統文化・工芸(和風)・歴史・文学・偉人)</option>
        <option value="博物館(美術・芸術・工芸(洋風)・絵・音楽)">博物館(美術・芸術・工芸(洋風)・絵・音楽)</option>
        <option value="博物館(科学技術・宇宙・産業・工業製品・特産品)">博物館(科学技術・宇宙・産業・工業製品・特産品)</option>
        <option value="博物館(自然・環境)">博物館(自然・環境)</option>
        <option value="食べ物・お酒・ワインなどに関する施設及び博物館">食べ物・お酒・ワインなどに関する施設及び博物館</option>
        <option value="その他観光名所(街並み・通り・道・湧水・シンボル・名物・展示など)">その他観光名所(街並み・通り・道・湧水・シンボル・名物・展示など)</option>
        <option value="ご飯屋・レストラン・カフェ">ご飯屋・レストラン・カフェ</option>
        <option value="買い物・お土産屋・市場">買い物・お土産屋・市場</option>
        <option value="宿泊施設・温泉施設(足湯含む)">宿泊施設・温泉施設(足湯含む)</option>
        <option value="サービスエリア・道の駅・鉄道駅">サービスエリア・道の駅・鉄道駅</option>
        <option value="案内所">案内所</option>
      </select>
      <li class="nav-item mt-1">
        <div id="search-container">
            <input id="pac-input" class="controls" type="text" placeholder="検索...">
            <button id="search-button" class="btn btn-primary btn-sm">検索</button>
        </div>
      </li>
      <li class="nav-item">
        <div id="map-control-container" class="nav-link">
          <button id="toggle-traffic" class="btn btn-success btn-sm me-1 mb-1 toggle-button">交通情報</button>
          <button id="toggle-transit" class="btn btn-secondary btn-sm me-1 mb-1 toggle-button">道路番号情報</button>
          <button id="toggle-tourist-spots" class="btn btn-success btn-sm mb-1 toggle-button">観光地情報</button>
        </div>
      </li>
    </ul>
  <% end %>
</header>